# Generated by Django 4.2.3 on 2023-07-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[(1, "ShipperCompany"), (2, "CarrierCompany")],
                default=1,
                max_length=10,
            ),
        ),
    ]
