# Generated by Django 4.2.3 on 2023-07-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="isDengerouse",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.IntegerField(
                choices=[(1, "ShipperCompany"), (2, "CarrierCompany")], default=1
            ),
        ),
    ]
